version: "3.8"

services:

  go-db:
    image: "postgres:14-alpine"
    container_name: go-db
    restart: on-failure
    ports:
      - 1111:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TheAnswerIsPosgres42!
      - POSTGRES_DB=go-db  